should_upload: true
workload_name: 'MicrosoftIIS'
workload_display_name: 'Microsoft IIS'
local_workload_icon_path: 'manifests/launch-wizard/icon.png'
workload_description: 'Deploys IIS into an Amazon Elastic Compute Cloud (Amazon EC2) Auto Scaling group.'
workload_versions:
  - deployment_option_name: 'Microsoft-IIS-New-VPC'
    deployment_option_description: 'Deploys IIS in a new VPC'
    deployment_option_display_name: 'Deploys IIS in a new VPC'
    version_name: '2022-03-23-05'
    version_description: '2022-03-23-05'
    ssm_document_name: 'AWSQuickStarts-Microsoft-IIS'
    local_metadata_file_path: 'manifests/launch-wizard/iisNewVpcMetadata.json'
    local_help_panel_folder_path: 'manifests/launch-wizard/new-vpc-help-panels'
  - deployment_option_name: 'Microsoft-IIS-Existing-VPC'
    deployment_option_description: 'Deploys IIS in an existing VPC'
    deployment_option_display_name: 'Deploys IIS in an existing VPC'
    version_name: '2022-03-23-05'
    version_description: '2022-03-23-05'
    ssm_document_name: 'AWSQuickStarts-Microsoft-IIS-Existing-VPC'
    local_metadata_file_path: 'manifests/launch-wizard/iisExistingVpcMetadata.json'
    local_help_panel_folder_path: 'manifests/launch-wizard/existing-vpc-help-panels'